services:
  #This is the database and instructions for docker to eventually store the calls so we don't use too many requests.
  db:
    image: postgres:15
    healthcheck: #trying to ensure the DB is ready before flask starts, this should help with the connection issues.
      test: ["CMD-SHELL", "pg_isready -U postgres -d recommender"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: recommender_db
    environment:
    POSTGRES_DB: ${DB_NAME}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - recommender-network
  backend:
    depends_on:
      db:
        condition: service_healthy

    #This is the backend (FLASK)
    build: ./backend #this looks for the Dockerfile with instructions for the build
    container_name: recommender_backend
    env_file: .env #added .env instructions as movies were not being fetched successfully
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "5000:5000" #enables the port so we can use flask on it and get results from the requests.
    networks:
      - recommender-network #the bridge between flask and the database so they can communicate
    volumes:
      - ./backend:/app #this account for any changes in the code so they are updated in docker

  frontend: #added frontend support
    image: nginx:alpine
    container_name: recommender_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro #this mounts the nginx.conf file to the correct location in the container, ensuring that nginx serves the frontend correctly.
    networks:
      - recommender-network
    depends_on:
      - backend

networks:
  recommender-network: #same as above, a communicator between the services.
    driver: bridge

volumes:
  pgdata: #physical storage space for DB files
