services:
  - type: web
    name: litflick-backend
    runtime: docker
    # Dockerfile is inside the backend folder
    dockerfilePath: ./backend/Dockerfile
    # Ensure your context is set correctly if needed
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: litflick-db
          property: connectionString
      - key: JWT_SECRET_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: GOOGLE_BOOKS_KEY
        sync: false
      - key: WEBHOOK_SECRET
        sync: false

  - type: static_site
    name: litflick-frontend
    publishPath: ./frontend
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

databases:
  - name: litflick-db
    databaseName: recommender
    plan: free
