name: CI Pipeline

on:
  push:
    branches: [Main, dev, feature/*, Feature/*]
  pull_request:
    branches: [Main, dev, feature/*]

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      DB_NAME: recommender
      DB_USER: postgres
      DB_PASS: ${{ secrets.DB_PASS }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      GOOGLE_BOOKS_KEY: ${{ secrets.GOOGLE_BOOKS_KEY }}

    steps:
      #Check the code
      - name: Checkout Code
        uses: actions/checkout@v3

        #Set up python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      #Check for Python syntax errors in the backend code
      - name: Python Syntax Check
        run: |
          python -m py_compile backend/*.py
          python -m py_compile backend/routes/*.py

      # Intall dependencies
      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      #Lint code
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 backend/ --count --max-line-length=120 --statistics || true

      #Build docker containers
      - name: Build Docker Containers
        run: docker compose build

      #Start containers
      - name: Start Containers
        run: |
          docker compose up -d
          sleep 15
      #Wait for the backend to be healthy before proceeding with tests
      - name: Wait for backend via Nginx
        run: |
          for i in {1..10}; do
            if curl -f http://localhost; then # Changed 5000 to 80 (default)
              echo "Backend reachable via Nginx!"
              exit 0
            fi
            sleep 5
          done
          exit 1
        #This loop will wait up to 100 seconds for the backend to become healthy before proceeding.

        #Show logs for debugging if the backend doesn't become healthy
      - name: Show container logs
        run: docker compose logs

      - name: Health check frontend
        run: |
          # Changed 8080 to 80
          curl --fail http://localhost || exit 1

      - name: Run unit tests
        run: |
          cd backend
          pip install pytest
          pytest tests/ -v

      #Clean up
      - name: Stop Containers
        if: always()
        run: docker compose down

      - name: Debug DB env
        run: |
          echo "DB_PASS=${DB_PASS:+SET}"
